In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df=pd.read_csv(r"C:\Users\shubh\Downloads\archive (23)\final_dataset_BFP .csv")
df.head()

Weight    Height        BMI  Body Fat Percentage     BFPcase  Gender  \
0  76.811975  1.820521  23.175956            18.281148  Acceptable    Male   
1  77.721154  1.945498  20.534184            13.731021     Fitness    Male   
2  87.558726  1.742754  28.828859            42.304631       Obese  Female   
3  89.473356  1.758318  28.940017            27.958021       Obese    Male   
4  69.963943  1.722570  23.578732            16.464478     Fitness    Male   

   Age      BMIcase  Exercise Recommendation Plan  
0   29       normal                             4  
1   23       normal                             4  
2   57  over weight                             5  
3   41  over weight                             5  
4   19       normal                             4

In [4]:
df.dtypes

Weight                          float64
Height                          float64
BMI                             float64
Body Fat Percentage             float64
BFPcase                          object
Gender                           object
Age                               int64
BMIcase                          object
Exercise Recommendation Plan      int64
dtype: object

In [5]:
df.isnull().sum()

Weight                          0
Height                          0
BMI                             0
Body Fat Percentage             0
BFPcase                         0
Gender                          0
Age                             0
BMIcase                         0
Exercise Recommendation Plan    0
dtype: int64

In [13]:
df['Exercise Recommendation Plan'].value_counts()

Exercise Recommendation Plan
4    1458
5    1230
7     860
6     843
3     263
1     211
2     135
Name: count, dtype: int64

In [6]:
cat_col=['BFPcase','Gender','BMIcase']

In [7]:
#changing the dataype from object to int
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for i in cat_col:
    df[i]=le.fit_transform(df[i])

In [8]:
df.head(2)

Weight    Height        BMI  Body Fat Percentage  BFPcase  Gender  Age  \
0  76.811975  1.820521  23.175956            18.281148        0       1   29   
1  77.721154  1.945498  20.534184            13.731021        2       1   23   

   BMIcase  Exercise Recommendation Plan  
0        2                             4  
1        2                             4

In [9]:
#splitting the data into dependent and independent varaibles
x=df.drop('Exercise Recommendation Plan',axis=1)
y=df['Exercise Recommendation Plan']

In [12]:
#training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2)
print(len(x_train))
print(len(x_test))

4000
1000


In [14]:
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

In [31]:
def eval_mod(ytest,ypred):
    print('classification_report \n',classification_report(ytest,ypred))
    print('confusion_matrix \n',confusion_matrix(ytest,ypred))
    print('accuracy_score \n',accuracy_score(ytest,ypred))

def mscore(model):
    print('Training score:',model.score(x_train,y_train))
    print('Testing score:', model.score(x_test,y_test))

k-Neighbour

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

knn.fit(x_train,y_train)

KNeighborsClassifier()

In [17]:
mscore(knn)

Training score: 0.9465
Testing score: 0.904


Decision Tree Classifier

In [18]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [19]:
mscore(dtc)

Training score: 1.0
Testing score: 1.0


Random Forest Classifier

In [20]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [21]:
mscore(rfc)

Training score: 1.0
Testing score: 1.0


In [28]:
ypred_rfc=rfc.predict(x_test)
ypred_rfc[:10]

array([4, 5, 6, 7, 4, 4, 4, 5, 7, 4], dtype=int64)

In [32]:
eval_mod(y_test,ypred_rfc)

classification_report 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        41
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        47
           4       1.00      1.00      1.00       309
           5       1.00      1.00      1.00       240
           6       1.00      1.00      1.00       173
           7       1.00      1.00      1.00       167

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

confusion_matrix 
 [[ 41   0   0   0   0   0   0]
 [  0  23   0   0   0   0   0]
 [  0   0  47   0   0   0   0]
 [  0   0   0 309   0   0   0]
 [  0   0   0   0 240   0   0]
 [  0   0   0   0   0 173   0]
 [  0   0   0   0   0   0 167]]
accuracy_score 
 1.0
